// Code generated by entc, DO NOT EDIT.

package section

import (
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the section type in the database.
	Label = "section"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// EdgeLayout holds the string denoting the layout edge name in mutations.
	EdgeLayout = "layout"
	// EdgeRows holds the string denoting the rows edge name in mutations.
	EdgeRows = "rows"
	// Table holds the table name of the section in the database.
	Table = "sections"
	// LayoutTable is the table that holds the layout relation/edge.
	LayoutTable = "sections"
	// LayoutInverseTable is the table name for the Layout entity.
	// It exists in this package in order to avoid circular dependency with the "layout" package.
	LayoutInverseTable = "layouts"
	// LayoutColumn is the table column denoting the layout relation/edge.
	LayoutColumn = "layout_sections"
	// RowsTable is the table that holds the rows relation/edge.
	RowsTable = "rows"
	// RowsInverseTable is the table name for the Row entity.
	// It exists in this package in order to avoid circular dependency with the "row" package.
	RowsInverseTable = "rows"
	// RowsColumn is the table column denoting the rows relation/edge.
	RowsColumn = "section_rows"
)

// Columns holds all SQL columns for section fields.
var Columns = []string{
	FieldID,
	FieldName,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "sections"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"layout_sections",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
