// Code generated by entc, DO NOT EDIT.

package layout

import (
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the layout type in the database.
	Label = "layout"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// EdgeEvents holds the string denoting the events edge name in mutations.
	EdgeEvents = "events"
	// EdgeSections holds the string denoting the sections edge name in mutations.
	EdgeSections = "sections"
	// Table holds the table name of the layout in the database.
	Table = "layouts"
	// EventsTable is the table that holds the events relation/edge.
	EventsTable = "events"
	// EventsInverseTable is the table name for the Event entity.
	// It exists in this package in order to avoid circular dependency with the "event" package.
	EventsInverseTable = "events"
	// EventsColumn is the table column denoting the events relation/edge.
	EventsColumn = "layout_events"
	// SectionsTable is the table that holds the sections relation/edge.
	SectionsTable = "sections"
	// SectionsInverseTable is the table name for the Section entity.
	// It exists in this package in order to avoid circular dependency with the "section" package.
	SectionsInverseTable = "sections"
	// SectionsColumn is the table column denoting the sections relation/edge.
	SectionsColumn = "layout_sections"
)

// Columns holds all SQL columns for layout fields.
var Columns = []string{
	FieldID,
	FieldName,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
