// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Event is the predicate function for event builders.
type Event func(*sql.Selector)

// Layout is the predicate function for layout builders.
type Layout func(*sql.Selector)

// Reservation is the predicate function for reservation builders.
type Reservation func(*sql.Selector)

// Row is the predicate function for row builders.
type Row func(*sql.Selector)

// Seat is the predicate function for seat builders.
type Seat func(*sql.Selector)

// Section is the predicate function for section builders.
type Section func(*sql.Selector)

// Ticket is the predicate function for ticket builders.
type Ticket func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
